default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  port: 5432
  username: postgres
  password: Selamento17*
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: v360_case_development

test:
  <<: *default
  database: v360_case_test

production:
  primary: &primary_production
    url: <%= ENV["DATABASE_URL"] %>
    pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

  cache:
    <<: *primary_production
    database: v360_case_production_cache
    migrations_paths: db/cache_migrate

  queue:
    <<: *primary_production
    database: v360_case_production_queue
    migrations_paths: db/queue_migrate

  cable:
    <<: *primary_production
    database: v360_case_production_cable
    migrations_paths: db/cable_migrate
 